module: User
routes:
  - path: /ping
    handler: Modules\User\Handler::ping
    methods: [GET]

  - path: /profile
    handler: Modules\User\Handler::profile
    methods: [GET]
    middleware: [auth]

  - path: /check/{id}
    handler: Modules\User\Handler::check
    methods: [GET]
