module: Scrape
routes:
  - path: /scrape/ig/post
    handler: Modules\Scrape\Http\ScrapeHandler::igPost
    methods: [GET]
  - path: /scrape/ig/profile
    handler: Modules\Scrape\Http\ScrapeHandler::igProfile
    methods: [GET]
  - path: /scrape/ig/feed
    handler: Modules\Scrape\Http\ScrapeHandler::igFeed
    methods: [GET]
