module: Auth
group: auth
routes:
  - path: /register
    handler: Modules\Auth\Http\AuthHandler::register
    methods: [POST]
  - path: /token
    handler: Modules\Auth\Http\AuthHandler::token
    methods: [POST]
