routes:
  - path: /ping
    handler: Modules\User\Handlers\UserHandler::ping
    methods: [GET]

  - path: /profile
    handler: Modules\User\Handlers\UserHandler::profile
    methods: [GET]
    middleware: [auth]

  - path: /check/{id}
    handler: Modules\User\Handlers\UserHandler::check
    methods: [GET]
