module: Home
routes:
  - path: /
    handler: Modules\Home\Http\HomeHandler::index
    methods: [GET]
  - path: /path/{id}
    handler: Modules\Home\Http\HomeHandler::path
    methods: [GET]
  - path: /dump
    handler: Modules\Home\Http\HomeHandler::dump
    methods: [GET]
